apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-config
  namespace: development

data: 
  index: |
    <h1>Hello world!</h1>
    <p>This is HTML from Kubernetes ConfigMap</p>

  different-index: |
    <h1>Hello world from different pod!</h1>
    <p>This is a load balancing test</p>

  hello: |
    <h2>Another hello world!<h2>

  kube-info-config: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root /usr/share/nginx/html-kube-info;
          index kube-info.html;
      }

      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
