apiVersion: apps/v1
kind: Deployment

metadata:
  name: test-templated

spec:
  selector:
    matchLabels:
      whatIsThis: APodFromDeployment

  template:
    metadata:
      labels:
        whatIsThis: APodFromDeployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80

  replicas: 4
