apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-test

namePrefix: nginx-experiment-
nameSuffix: -suffix

labels:
  - pairs:
      useCase: nginx-experiment
      owner: JiriFilip

commonAnnotations:
  x-pepik.cz/blablabla: test

resources:
  - base/namespace.yaml
  - base/pod.yaml

configMapGenerator:
  - name: config-test
    files:
      - files/config.json
